linters:
  disable-all: true
  enable:
    - gofumpt
    - govet
    - gci
    - staticcheck

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - prefix(github.com/sithu015/)
      - default
  staticcheck:
    go: '1.20'
